apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: bitnami-postgresql
  namespace: shelfshare-localprod
spec:
  interval: 10m
  url: oci://registry-1.docker.io/bitnamicharts/postgresql
  ref:
    tag: 18.1.0
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
