apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - apps/namespace.yaml
  - apps/traefik/helmrepository.yaml
  - apps/traefik/helmrelease.yaml
  - apps/traefik/values.sops.yaml
  - apps/postgres/helmrepository.yaml
  - apps/postgres/helmrelease.yaml
  - apps/postgres/values.sops.yaml
  - apps/envoy/helmrelease.yaml
  - apps/books-service
  - sources/postgres-oci.yaml
