apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-components.yaml
  - gotk-sync.yaml
  - shelfshare-localprod-kustomization.yaml
  - image-repository-books-service.yaml
  - image-policy-books-service.yaml
  - image-update-automation.yaml
