apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: shelfshare-localprod
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./k8s/localprod
  prune: true
  targetNamespace: shelfshare-localprod
  decryption:
    provider: sops
    secretRef:
      name: sops-age
