[all]
localhost ansible_connection=local

[local_fluxcd]
localhost ansible_connection=local

[wireguard_server]

[wireguard_clients]
local ansible_connection=local ansible_user=sinaniya wg_address=10.10.0.2/32

[wireguard:children]
wireguard_server
wireguard_clients

[k3s_servers]

[k3s_servers:vars]
ansible_python_interpreter=/usr/bin/python3
